import {
  Activity,
  Apple,
  BatteryMedium,
  Bed,
  Beer,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Candy,
  Cigarette,
  Clock,
  Code,
  Coffee,
  Droplets,
  Dumbbell,
  Flame,
  Focus,
  Footprints,
  Gamepad2,
  GlassWater,
  GraduationCap,
  HeartPulse,
  Hourglass,
  House,
  Languages,
  Leaf,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Palette,
  PenLine,
  PiggyBank,
  Salad,
  ShowerHead,
  Smartphone,
  Smile,
  Snowflake,
  Sun,
  Target,
  Tv,
  Users,
  Utensils,
  Ban,
  Wind,
  Wine,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from '../../domain/types';

/** Ключ из данных → картинка. Новая иконка: ключ в domain/icons.ts + строка здесь. */
export const HABIT_ICONS: Record<IconName, LucideIcon> = {
  dumbbell: Dumbbell,
  bike: Bike,
  footprints: Footprints,
  activity: Activity,
  'heart-pulse': HeartPulse,
  mountain: Mountain,
  moon: Moon,
  bed: Bed,
  sun: Sun,
  clock: Clock,
  hourglass: Hourglass,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  brain: Brain,
  'pen-line': PenLine,
  'notebook-pen': NotebookPen,
  code: Code,
  languages: Languages,
  briefcase: Briefcase,
  target: Target,
  music: Music,
  palette: Palette,
  'glass-water': GlassWater,
  droplets: Droplets,
  apple: Apple,
  salad: Salad,
  utensils: Utensils,
  coffee: Coffee,
  cigarette: Cigarette,
  wine: Wine,
  beer: Beer,
  candy: Candy,
  smartphone: Smartphone,
  gamepad: Gamepad2,
  tv: Tv,
  ban: Ban,
  'shower-head': ShowerHead,
  snowflake: Snowflake,
  leaf: Leaf,
  wind: Wind,
  flame: Flame,
  zap: Zap,
  'piggy-bank': PiggyBank,
  users: Users,
  house: House,
  smile: Smile,
  focus: Focus,
  battery: BatteryMedium,
};

/** Названия иконок для скринридера. */
export const ICON_LABELS: Record<IconName, string> = {
  dumbbell: 'Гантель',
  bike: 'Велосипед',
  footprints: 'Шаги',
  activity: 'Пульс',
  'heart-pulse': 'Сердце',
  mountain: 'Гора',
  moon: 'Луна',
  bed: 'Кровать',
  sun: 'Солнце',
  clock: 'Часы',
  hourglass: 'Песочные часы',
  'book-open': 'Книга',
  'graduation-cap': 'Учёба',
  brain: 'Мозг',
  'pen-line': 'Ручка',
  'notebook-pen': 'Блокнот',
  code: 'Код',
  languages: 'Языки',
  briefcase: 'Работа',
  target: 'Цель',
  music: 'Музыка',
  palette: 'Палитра',
  'glass-water': 'Стакан воды',
  droplets: 'Капли',
  apple: 'Яблоко',
  salad: 'Салат',
  utensils: 'Еда',
  coffee: 'Кофе',
  cigarette: 'Сигарета',
  wine: 'Вино',
  beer: 'Пиво',
  candy: 'Конфета',
  smartphone: 'Телефон',
  gamepad: 'Игры',
  tv: 'Телевизор',
  ban: 'Запрет',
  'shower-head': 'Душ',
  snowflake: 'Снежинка',
  leaf: 'Лист',
  wind: 'Ветер',
  flame: 'Огонь',
  zap: 'Молния',
  'piggy-bank': 'Копилка',
  users: 'Люди',
  house: 'Дом',
  smile: 'Улыбка',
  focus: 'Фокус',
  battery: 'Батарея',
};
